"""Fixed template wording for the backend Copilot; facts remain in services."""

COPILOT_TEMPLATES = {
    "en": {
        "unavailable": "Data unavailable for this area.",
        "select_street": "Click a street in the risk map to see its explanation.",
        "select_time": "Choose a time in the planner to explain this street's risk.",
        "route_need_endpoints": "Tell me the origin and destination, for example: A se B jaana hai.",
        "route_need_time": "Choose a departure time in the citizen route planner first.",
        "route_ambiguous": "I found these place matches: {matches}. Which one did you mean?",
        "route_summary": "Route options from {origin} to {destination} at {time}: {routes}. {recommendation}",
        "route_item": "{name}: {minutes} min, {distance} m, modelled heat exposure {heat}, shade {shade}%",
        "risk_summary": "At {time}, {street} has modelled priority {score} ({risk_class}). Main drivers: {drivers}.",
        "risk_driver": "{label}: {level} ({value})",
        "stops_need_route": "Provide a route in context, or tell me its origin and destination.",
        "stops_summary": "For the {route_name} route: {status}. {items}",
        "stop_item": "{name} ({kind}), {distance} m from the route, {detour} m detour{amenities}.",
        "stop_amenities": "; amenities: {amenities}",
        "planner_default": "I could not parse resource counts, so I used the configured defaults: {counts}.",
        "planner_summary": "The optimizer's ordered plan is {priorities}. Modelled objective: {before} before and {after} after, a reduction of {reduction}. Modelled Impact: {metrics}.",
        "planner_priority": "{number}. {kind} at {place}: {share}% of total modelled reduction",
        "planner_no_actions": "The optimizer found no positive-impact actions for those resource counts.",
        "data_height": "Building heights use observed OSM height first, then OSM levels times {per_floor} m, then the configured {fallback} m fallback. Cached-building counts: {counts}.",
        "data_vulnerability": "Vulnerability is a density-based proxy from cached OSM building area and available activity proxies, not a population count. Method: {method}.",
        "data_normalization": "Risk scores use {method} with scope {scope}; categories are modelled prioritization classes, not medical thresholds.",
        "data_temperature": "The configured hourly temperature curve ({curve}) is a prototype assumption, not an observed temperature or medical measurement: {assumption}",
        "data_facilities": "Only recorded OSM facilities count as existing facilities. Cached counts: {water} water and {cooling} cooling facilities. Missing coverage remains unavailable.",
        "data_overview": "Available provenance: building-height hierarchy {height}; vulnerability proxy {vulnerability}; score normalization {normalization}; temperature proxy {temperature}; facility limits {facilities}.",
        "symptoms": "I cannot assess symptoms. Please seek medical help immediately. In India, call 108 for an ambulance or 112 for emergency assistance.",
        "tips_intro": "General heat guidance:",
        "tips_item": "{tip}",
        "scene_route": "Route guidance: {recommendation} Stop information: {stops} General tips: {tips}",
        "platform": "Use the map to select a street, choose a time, and open its WHY explanation. In Citizen view, enter an origin and destination to compare route options. The displayed categories and route values are modelled outputs, not personal measurements.",
        "unknown": "I can explain the platform, a selected street's risk, routes and recorded stops, resource plans, data assumptions, and general heat guidance. Try: {examples}.",
        "unknown_examples": "How do I use the time slider?; Why is this street high risk?; A se B jaana hai; How were building heights estimated?",
        "tip_join": "; ",
        "count_item": "{count} {name}",
        "percent": "{value}%",
        "not_recorded": "No recorded eligible stops.",
        "platform_planner": "Current view: Planner. Select a street and time for risk details, or set resource counts to request an optimized plan.",
        "platform_citizen": "Current view: Citizen. Set an origin, destination, and departure time to compare routes and recorded stops.",
        "route_assumption": "Route calculations apply the departure-time snapshot across the whole trip; conditions are not modelled as changing while travelling.",
        "vulnerability_assumption": "Vulnerability is a density-based proxy, not a count of people.",
        "temperature_assumption": "The temperature curve is a prototype assumption, not an observed measurement.",
        "planner_assumption": "The optimizer reports modelled impact over its configured scope; it is not a measured outcome.",
    },
    "hi": {
        "unavailable": "इस क्षेत्र के लिए डेटा उपलब्ध नहीं है।",
        "select_street": "इसकी जानकारी देखने के लिए जोखिम मानचित्र पर सड़क चुनें।",
        "select_time": "इस सड़क के जोखिम की जानकारी के लिए प्लानर में समय चुनें।",
        "route_need_endpoints": "शुरुआत और मंज़िल बताएं, जैसे: A se B jaana hai।",
        "route_need_time": "पहले नागरिक मार्ग योजनाकार में रवाना होने का समय चुनें।",
        "route_ambiguous": "जगहों के ये मेल मिले: {matches}। आपका मतलब किससे है?",
        "route_summary": "{origin} से {destination} के लिए {time} पर मार्ग विकल्प: {routes}। {recommendation}",
        "route_item": "{name}: {minutes} मिनट, {distance} मीटर, गर्मी का मॉडल-अनुमान {heat}, छाया {shade}%",
        "risk_summary": "{time} पर {street} की मॉडल प्राथमिकता {score} ({risk_class}) है। मुख्य कारण: {drivers}।",
        "risk_driver": "{label}: {level} ({value})",
        "stops_need_route": "संदर्भ में मार्ग दें या उसकी शुरुआत और मंज़िल बताएं।",
        "stops_summary": "{route_name} मार्ग के लिए: {status}। {items}",
        "stop_item": "{name} ({kind}), मार्ग से {distance} मीटर दूर, अतिरिक्त दूरी {detour} मीटर{amenities}।",
        "stop_amenities": "; सुविधाएँ: {amenities}",
        "planner_default": "संसाधनों की संख्या समझ नहीं आई, इसलिए तय डिफ़ॉल्ट उपयोग किए: {counts}।",
        "planner_summary": "अनुकूलक की प्राथमिकता के क्रम वाली योजना: {priorities}। मॉडल उद्देश्य {before} से घटकर {after} हुआ; कमी {reduction}। मॉडल प्रभाव: {metrics}।",
        "planner_priority": "{number}. {place} पर {kind}: कुल मॉडल कमी का {share}%",
        "planner_no_actions": "इन संसाधन संख्याओं के लिए अनुकूलक को सकारात्मक प्रभाव वाली कार्रवाई नहीं मिली।",
        "data_height": "इमारत की ऊँचाई में पहले दर्ज OSM ऊँचाई, फिर OSM मंज़िलों को {per_floor} मीटर से गुणा करके, और अंत में तय {fallback} मीटर डिफ़ॉल्ट उपयोग होता है। सहेजी इमारतों की संख्या: {counts}।",
        "data_vulnerability": "कमज़ोरी का अनुमान सहेजे OSM इमारत क्षेत्र और उपलब्ध गतिविधि संकेतों पर आधारित घनत्व प्रॉक्सी है; यह जनसंख्या की गिनती नहीं है। तरीका: {method}।",
        "data_normalization": "जोखिम स्कोर {method} से सामान्यीकृत हैं; दायरा {scope} है। श्रेणियाँ मॉडल प्राथमिकता हैं, चिकित्सा सीमा नहीं।",
        "data_temperature": "तय घंटेवार तापमान वक्र ({curve}) प्रोटोटाइप की धारणा है, देखा गया तापमान या चिकित्सीय माप नहीं: {assumption}",
        "data_facilities": "मौजूदा सुविधा केवल दर्ज OSM सुविधा है। सहेजे डेटा में {water} पानी और {cooling} ठंडक सुविधाएँ हैं। कमी होने पर जानकारी उपलब्ध नहीं मानी जाती।",
        "data_overview": "उपलब्ध स्रोत जानकारी: इमारत ऊँचाई का तरीका {height}; कमज़ोरी प्रॉक्सी {vulnerability}; स्कोर सामान्यीकरण {normalization}; तापमान प्रॉक्सी {temperature}; सुविधा डेटा की सीमा {facilities}।",
        "symptoms": "मैं लक्षणों का आकलन नहीं कर सकता। कृपया तुरंत चिकित्सा सहायता लें। भारत में एम्बुलेंस के लिए 108 या आपात सहायता के लिए 112 पर कॉल करें।",
        "tips_intro": "गर्मी के लिए सामान्य सुझाव:",
        "tips_item": "{tip}",
        "scene_route": "मार्ग सुझाव: {recommendation} ठहराव की जानकारी: {stops} सामान्य सुझाव: {tips}",
        "platform": "मानचित्र पर सड़क चुनें, समय चुनें और उसकी WHY जानकारी खोलें। नागरिक दृश्य में मार्ग विकल्पों की तुलना के लिए शुरुआत और मंज़िल भरें। दिखाई गई श्रेणियाँ और मार्ग मान मॉडल पर आधारित हैं, किसी व्यक्ति का माप नहीं।",
        "unknown": "मैं मंच का उपयोग, चुनी सड़क का जोखिम, मार्ग और दर्ज ठहराव, संसाधन योजना, डेटा की धारणाएँ और गर्मी के सामान्य सुझाव समझा सकता हूँ। पूछें: {examples}।",
        "unknown_examples": "समय स्लाइडर कैसे इस्तेमाल करें?; इस सड़क का जोखिम अधिक क्यों है?; A से B तक कैसे जाएँ?; इमारतों की ऊँचाई का अनुमान कैसे लगा?",
        "tip_join": "; ",
        "count_item": "{count} {name}",
        "percent": "{value}%",
        "not_recorded": "कोई योग्य ठहराव दर्ज नहीं है।",
        "platform_planner": "अभी का दृश्य: प्लानर। जोखिम की जानकारी के लिए सड़क और समय चुनें, या संसाधन संख्या देकर योजना बनवाएँ।",
        "platform_citizen": "अभी का दृश्य: नागरिक। मार्गों और दर्ज ठहराव की तुलना के लिए शुरुआत, मंज़िल और रवाना होने का समय चुनें।",
        "route_assumption": "मार्ग की गणना में रवाना होने के समय का मॉडल पूरे सफ़र पर लागू होता है; यात्रा के दौरान बदलती स्थिति का हिसाब नहीं है।",
        "vulnerability_assumption": "कमज़ोरी का मान घनत्व पर आधारित प्रॉक्सी है, लोगों की गिनती नहीं।",
        "temperature_assumption": "तापमान वक्र प्रोटोटाइप की धारणा है, देखा गया माप नहीं।",
        "planner_assumption": "अनुकूलक अपने तय दायरे में मॉडल प्रभाव बताता है; यह मापा हुआ परिणाम नहीं है।",
    },
}


COPILOT_LABELS = {
    "en": {
        "resource_types": {"water_points": "water points", "cooling_centres": "cooling centres", "shade_structures": "shade structures"},
        "height_sources": {"observed_height": "observed height", "levels_derived": "levels-derived", "fallback_estimated": "fallback-estimated", "other": "other"},
        "drivers": {"solar_exposure": "Solar exposure", "shade": "Shade", "vulnerability": "Estimated vulnerability", "cooling_access_penalty": "Cooling access"},
        "levels": {"LOW": "low", "MODERATE": "moderate", "HIGH": "high", "GOOD": "good", "POOR": "poor"},
        "metrics": {"high_risk_vulnerable_exposure": "high-priority exposure", "intervention_coverage": "intervention coverage", "water_coverage": "water coverage", "cooling_coverage": "cooling coverage"},
        "sources": {},
        "vulnerability_method": "Sum cached OSM building footprint area whose centroid falls within a {buffer_m} m street buffer",
        "normalization_method": "global min-max normalization",
        "normalization_scope": "all five canonical snapshots",
        "temperature_assumption": "The configured hourly temperature curve is used only as a prototype proxy.",
    },
    "hi": {
        "resource_types": {"water_points": "पानी के स्थान", "cooling_centres": "ठंडक केंद्र", "shade_structures": "छाया संरचनाएँ"},
        "height_sources": {"observed_height": "दर्ज ऊँचाई", "levels_derived": "मंज़िलों से अनुमानित", "fallback_estimated": "डिफ़ॉल्ट से अनुमानित", "other": "अन्य"},
        "drivers": {"solar_exposure": "धूप का संपर्क", "shade": "छाया", "vulnerability": "अनुमानित कमज़ोरी", "cooling_access_penalty": "ठंडक सुविधा तक पहुँच"},
        "levels": {"LOW": "कम", "MODERATE": "मध्यम", "HIGH": "अधिक", "GOOD": "अच्छी", "POOR": "कम"},
        "metrics": {"high_risk_vulnerable_exposure": "अधिक प्राथमिकता वाले क्षेत्र का संपर्क", "intervention_coverage": "हस्तक्षेप का कवरेज", "water_coverage": "पानी का कवरेज", "cooling_coverage": "ठंडक का कवरेज"},
        "sources": {
            "versioned configuration": "संस्करण वाली सेटिंग",
            "cached building records": "सहेजे भवन रिकॉर्ड",
            "cached vulnerability provenance": "सहेजे कमज़ोरी स्रोत विवरण",
            "risk normalization configuration": "जोखिम सामान्यीकरण सेटिंग",
            "cached exposure provenance": "सहेजे संपर्क विवरण",
            "cached facility coverage": "सहेजी सुविधा उपलब्धता",
            "deterministic optimizer plan": "नियत अनुकूलक योजना",
            "India emergency contact guidance": "भारत की आपात संपर्क जानकारी",
            "approved citizen heat guidance": "स्वीकृत सामान्य गर्मी सुझाव",
            "platform help": "मंच उपयोग सहायता",
            "Copilot help": "Copilot सहायता",
        },
        "vulnerability_method": "सड़क से {buffer_m} मीटर के दायरे में आने वाले सहेजे OSM भवन क्षेत्र का योग",
        "normalization_method": "सभी पाँच समय-बिंदुओं पर वैश्विक min-max सामान्यीकरण",
        "normalization_scope": "सभी पाँच तय समय-बिंदु",
        "temperature_assumption": "तय घंटेवार तापमान वक्र केवल प्रोटोटाइप अनुमान के रूप में उपयोग होता है।",
    },
}
